.TH arm 1 "27 August 2010"
.SH NAME
arm - Terminal Tor status monitor

.SH SYNOPSIS
arm [\fIOPTION\fR]

.SH DESCRIPTION
The anonymizing relay monitor (arm) is a terminal status monitor for Tor
relays, intended for command-line aficionados, ssh connections, and anyone
stuck with a tty terminal. This works much like top does for system usage,
providing real time statistics for:
  * bandwidth, cpu, and memory usage
  * relay's current configuration
  * logged events
  * connection details (ip, hostname, fingerprint, and consensus data)
  * etc

Defaults and interface properties are configurable via a user provided
configuration file (for an example see the provided \fBarmrc.sample\fR).
Releases and information are available at \fIhttp://www.atagar.com/arm\fR.

.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-interface [ADDRESS:]PORT\fR
tor control port arm should attach to (default is \fB127.0.0.1:9051\fR)

.TP
\fB\-c\fR, \fB\-\-config CONFIG_PATH\fR
user provided configuration file (default is \fB~/.arm/armrc\fR)

.TP
\fB\-d\fR, \fB\-\-debug\fR
writes all arm logs to ~/.arm/log

.TP
\fB\-b\fR, \fB\-\-blind\fR
disable connection lookups (netstat, lsof, and ss), dropping the parts of the
interface that rely on this information

.TP
\fB\-e\fR, \fB\-\-event EVENT_FLAGS\fR
flags for tor, arm, and torctl events to be logged (default is \fBN3\fR)

  d DEBUG      a ADDRMAP           k DESCCHANGED   s STREAM
  i INFO       f AUTHDIR_NEWDESCS  g GUARD         r STREAM_BW
  n NOTICE     h BUILDTIMEOUT_SET  l NEWCONSENSUS  t STATUS_CLIENT
  w WARN       b BW                m NEWDESC       u STATUS_GENERAL
  e ERR        c CIRC              p NS            v STATUS_SERVER
               j CLIENTS_SEEN      q ORCONN
    DINWE tor runlevel+            A All Events
    12345 arm runlevel+            X No Events
    67890 torctl runlevel+         U Unknown Events

.TP
\fB\-v\fR, \fB\-\-version\fR
provides version information

.TP
\fB\-h\fR, \fB\-\-help\fR
provides usage information

.SH FILES
.TP
\fB~/.arm/armrc\fR
Your personal arm configuration file

.TP
\fB/usr/share/doc/arm/armrc.sample\fR
Sample armrc configuration file that documents all options

.SH AUTHOR
Written by Damian Johnson (atagar@torproject.org)

