#!/bin/sh
if [ $0 = /usr/bin/arm ]; then
  arm_base=/usr/share/pyshared/arm/
else
  arm_base=$( dirname $0 )/src/
fi

python ${arm_base}prereq.py

if [ $? = 0 ]; then
  python -W ignore::DeprecationWarning ${arm_base}starter.py $*
fi

