.TH arm 1 "24 August 2010"
.SH NAME
arm - Terminal Tor status monitor
.SH SYNOPSIS
arm [OPTION]
.SH DESCRIPTION

.B arm
is a terminal status monitor for
.B Tor
relays.

.SH OPTIONS

.B -h
.IP
Print usage information for
.B arm(1)
.P

.SH FILES
.B ~/.armrc
.IP
Optional user customized configuration
.P

