.TH nyx 1 "27 August 2010"
.SH NAME
nyx - Tor terminal status monitor

.SH SYNOPSIS
nyx [\fIOPTION\fR]

.SH DESCRIPTION
Nyx is a command line interface for Tor (https://www.torproject.org/),
providing detailed real-time relaying information for...

  * bandwidth, cpu, and memory usage
  * connection information
  * tor configuration
  * event logs
  * etc

As a curses interface Nyx is particularly well suited for ssh connections, tty 
terminals, and command-line aficionados to check the status of tor.

Nyx can be customized through a configuration file located at
\fB~/.nyx/config\fR. For options see
\fBhttps://nyx.torproject.org/#configuration\fR.

.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-interface [ADDRESS:]PORT\fR
tor control port we should attach to (default is \fB127.0.0.1:9051\fR)

.TP
\fB\-s\fR, \fB\-\-socket SOCKET_PATH\fR
tor control socket we should attach to (default is \fB/var/run/tor/control\fR)

.TP
\fB\-c\fR, \fB\-\-config CONFIG_PATH\fR
user configuration preferences (default is \fB~/.nyx/config\fR)

.TP
\fB\-d\fR, \fB\-\-debug LOG_PATH\fR
writes all nyx logs to the given location

.TP
\fB\-l\fR, \fB\-\-log EVENTS\fR
comma separated list of events to log

.TP
\fB\-v\fR, \fB\-\-version\fR
provides version information

.TP
\fB\-h\fR, \fB\-\-help\fR
provides usage information

.SH FILES
.TP
\fB~/.nyx/config\fR
Your personal nyx configuration file

.TP
\fB/usr/share/doc/nyx/config.sample\fR
Sample nyxconfig configuration file that documents all options

.SH AUTHOR
Written by Damian Johnson (atagar@torproject.org)

