#!/bin/sh

# Also looking in /bin/arm because of the UsrMove feature on Fedora...
# https://trac.torproject.org/5973

if [ "$0" = /usr/bin/arm ] || [ "$0" = /bin/arm ]; then
  arm_base=/usr/share/arm/
else
  arm_base=$( dirname "$0" )/arm/
fi

python "${arm_base}prereq.py" $*

if [ $? = 0 ]; then
  exec python -W ignore::DeprecationWarning "runner.py" $*
fi

