#!/usr/bin/env python
# Copyright 2014, Damian Johnson and The Tor Project
# See LICENSE for licensing information

import sys

import arm.starter

def main():
  try:
    _check_prereq()
  except ImportError as exc:
    print exc
    sys.exit(1)

  arm.starter.main()


def _check_prereq():
  """
  Checks for arm's prerequisistes...

    * python 2.6 or later
    * stem
    * curses

  :raises: **ImportError** if any of our prerequisites aren't met
  """

  major_version, minor_version = sys.version_info[0:2]

  if major_version < 2 or (major_version == 2 and minor_version < 6):
    raise ImportError("arm requires python version 2.6 or greater")

  try:
    import stem
  except ImportError:
    raise ImportError("arm requires stem, try running 'sudo apt-get install python-stem'")

  try:
    import curses
  except ImportError:
    raise ImportError("arm requires curses, try running 'sudo apt-get install python-curses'")


if __name__ == '__main__':
  main()
