#!/bin/sh
files="/usr/bin/nyx /usr/share/man/man1/nyx.1.gz /usr/share/nyx"

for i in $files
do
  if [ -f $i -o -d $i ]; then
    rm -rf $i
    
    if [ $? = 0 ]; then
      echo "removed $i"
    else
      exit 1
    fi
  fi
done

