.TH seth 1 "27 August 2010"
.SH NAME
seth - Terminal Tor status monitor

.SH SYNOPSIS
seth [\fIOPTION\fR]

.SH DESCRIPTION
The anonymizing relay monitor (seth) is a terminal status monitor for Tor
relays, intended for command-line aficionados, ssh connections, and anyone
stuck with a tty terminal. This works much like top does for system usage,
providing real time statistics for:
  * bandwidth, cpu, and memory usage
  * relay's current configuration
  * logged events
  * connection details (ip, hostname, fingerprint, and consensus data)
  * etc

Defaults and interface properties are configurable via a user provided
configuration file (for an example see the provided \fBsethrc.sample\fR).
Releases and information are available at \fIhttp://www.atagar.com/seth\fR.

.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-interface [ADDRESS:]PORT\fR
tor control port seth should attach to (default is \fB127.0.0.1:9051\fR)

.TP
\fB\-c\fR, \fB\-\-config CONFIG_PATH\fR
user provided configuration file (default is \fB~/.seth/sethrc\fR)

.TP
\fB\-d\fR, \fB\-\-debug\fR
writes all seth logs to ~/.seth/log

.TP
\fB\-e\fR, \fB\-\-event EVENT_FLAGS\fR
flags for tor, seth, and torctl events to be logged (default is \fBN3\fR)

  d DEBUG      a ADDRMAP           k DESCCHANGED   s STREAM
  i INFO       f AUTHDIR_NEWDESCS  g GUARD         r STREAM_BW
  n NOTICE     h BUILDTIMEOUT_SET  l NEWCONSENSUS  t STATUS_CLIENT
  w WARN       b BW                m NEWDESC       u STATUS_GENERAL
  e ERR        c CIRC              p NS            v STATUS_SERVER
               j CLIENTS_SEEN      q ORCONN
    DINWE tor runlevel+            A All Events
    12345 seth runlevel+            X No Events
    67890 torctl runlevel+         U Unknown Events

.TP
\fB\-v\fR, \fB\-\-version\fR
provides version information

.TP
\fB\-h\fR, \fB\-\-help\fR
provides usage information

.SH FILES
.TP
\fB~/.seth/sethrc\fR
Your personal seth configuration file

.TP
\fB/usr/share/doc/seth/sethrc.sample\fR
Sample sethrc configuration file that documents all options

.SH AUTHOR
Written by Damian Johnson (atagar@torproject.org)

