#!/bin/sh
cp debian/setup.cfg ./
cp debian/arm.1.gz ./
debuild -I.svn -i.svn -I.pyc -i.pyc

# cleans up after deb build
files="build debian/tor-arm debian/python-module-stampdir debian/tor-arm.debhelper.log debian/files debian/tor-arm.substvars setup.cfg arm.1.gz"

for i in $files 
do
  if [ -f $i -o -d $i ]; then
    rm -rf $i
    
    if [ $? = 0 ]; then
      echo "removed $i"
    else
      exit 1
    fi
  fi
done

