#!/bin/sh
cp debian/setup.cfg ./
cp debian/MANIFEST ./
python setup.py bdist_rpm

# cleans up after rpm build
files="build setup.cfg MANIFEST"

for i in $files 
do
  if [ -f $i -o -d $i ]; then
    rm -rf $i
    
    if [ $? = 0 ]; then
      echo "removed $i"
    else
      exit 1
    fi
  fi
done

